### ISSUE TITLE
Reproducing results from the paper

### ISSUE THREAD

**Issue by pauldb89** [patronus-ai/financebench#1]
I don't think it's possible to reproduce the shared store results from the paper without providing the full list of (360?) documents in addition to the (150) query / answer pairs. Some documents don't appear in any QA pair.

Separately, it would be great if the paper would offer more details about the vector store implementation. Are the documents split into chunks before being stored in the vector store? In particular, it would be helpful to know how the single store implementation is different from simply including the document in the context.

(it would be really awesome if you could just include the evaluation code from the paper in the repo.)

**Comment by PheelaV** [comment]
> I don't think it's possible to reproduce the shared store results from the paper without providing the full list of (360?) documents in addition to the (150) query / answer pairs. Some documents don't appear in any QA pair.
> 
> Separately, it would be great if the paper would offer more details about the vector store implementation. Are the documents split into chunks before being stored in the vector store? In particular, it would be helpful to know how the single store implementation is different from simply including the document in the context.
> 
> (it would be really awesome if you could just include the evaluation code from the paper in the repo.)

Let's re-label:

> INANCEBENCH: A ~New Benchmark~ **paid test service** for Financial Question Answering

The public would do better to ignore the paper as there is little contribution to the public domain. The business models seems to evolve around people trusting patronus-ai and paying to have their models run through a suite of real-world benchmarks. Fair enough, but the paper hence serves only as a tease for the academics and maybe inspiration for future work, otherwise it is an industry ad. Given enough built up credibility this might as well work for the industry. But who would include their original and cross-referenced results from a benchmark that is not accessible or easily replicable in their their writing?

**Comment by peteanderson80** [comment]
+1 to releasing the evaluation code from the paper, without it FinanceBench is not a bench.

**Comment by ninodimontalcino** [comment]
Hi @pauldb89 and @peteanderson80,

thanks for your interest in FinanceBench! We have just released an evaluation playground (Jupyter Notebook) with all evaluation settings, including PDF parsing (using `pymupdf`) and the construction of VectorStores (using `Chroma`). In addition, we also released the full set of relevant financial PDF documents.

Please let us know if you have any further questions.

**Comment by ninodimontalcino** [comment]
Hi @pauldb89 and @peteanderson80,

thanks for your interest in FinanceBench! We have just released an evaluation playground (Jupyter Notebook) with all evaluation settings, including PDF parsing (using `pymupdf`) and the construction of VectorStores (using `Chroma`). In addition, we also released the full set of relevant financial PDF documents.

Please let us know if you have any further questions.
