### ISSUE TITLE
About format of doc

### ISSUE THREAD

**Issue by zhouzihao501** [patronus-ai/financebench#3]

**Comment by zhouzihao501** [comment]
Hi, when you input the doc in model like GPT4, what's the format of doc(markdown?) and what's tool you use to transform pdf to this format?

**Comment by zhouzihao501** [comment]
thanks!

**Comment by ninodimontalcino** [comment]
Hi @zhouzihao501,

thanks for your interest in FinanceBench! We've just released an evaluation playground script where you can see how we parse PDFs and call LLMs with the relevant texts. For parsing, we use `pymupdf` -- note that different parsers may result in different results as tables are differently parsed. Please let us know if you have any further questions.
