### ISSUE TITLE
Release model answers and human evals

### ISSUE THREAD

**Issue by peteanderson80** [patronus-ai/financebench#4]
Thanks for releasing the eval script and source PDFs!

Will you release the model answers for the 16 configs in the paper and the human evals (i.e., correct, incorrect, fail to answer)?

This type of data is handy for validating automatic evaluations, and would be a great contribution as well.

**Comment by ninodimontalcino** [comment]
Hi Peter,

I've just released the human-annotated model answers for the 16 configs in the paper. Have fun with them!

Best,
Nino
