### ISSUE TITLE
Corrupted pdf INTEL_2023_8K_dated-2022-11-22.pdf

### ISSUE THREAD

**Issue by debadeepta** [patronus-ai/financebench#9]
Cannot be opened by Preview on Mac (throws up an error that it is possibly corrupted)
https://github.com/patronus-ai/financebench/blob/main/pdfs/INTEL_2023_8K_dated-2022-11-22.pdf

**Comment by sunitharavi9** [comment]
Hi! We have replaced the pdf. Let us know if you are still facing any issues

**Comment by debadeepta** [comment]
Works now. thanks :-)
